name: CPrefix Command
active: true
description: Command that allows you to configure the CPrefix for the bot.
class: CPrefix
key: cprefix
aliases:
  - cpfx
cooldown:
  global: 0
  user: 0
clients: '*'
directory: >-
  /Users/kserebour/Personal/Lavenza-II/app/core/talents/configure/hooks/Commands/Cprefix
id: cprefix
