name: Reminder Talent
description: >-
  Provides the capability to remind discord members about things they have to do
  in the future!
version: 0.2.0
class: Reminder
dependencies: []
clients:
  - discord
directory: /Users/kserebour/src/Personal/Lavenza-II/app/core/talents/reminder
