name: Sora
command_prefix: $
locale: en
talents:
  - examples
  - gestalt
  - dndiscord
  - smashbros
  - i18n
  - minigames
clients:
  - discord
  - twitch
directory: /Users/kserebour/src/Personal/Lavenza-II/app/bots/sora
