name: 8Ball Command
description: Ask a question to 8Ball! 8Ball is god and knows all...
class: EightBall
key: 8ball
aliases:
  - 8b
  - ball
cooldown:
  global: 0
  user: 5
clients: '*'
directory: /home/aigachu/apps/Lavenza-II/app/core/talents/minigames/hooks/Commands/8Ball
id: 8ball
