name: Ping Command
description: Command that simply orders the bot to say "Pong!"
class: Ping
key: ping
aliases:
  - pingu
  - pingo
cooldown:
  global: 0
  user: 0
clients: '*'
directory: /home/aigachu/apps/Lavenza-II/app/core/talents/examples/hooks/Commands/Ping
id: ping
