# Configure command parameters.
# This file is not obligatory.
# Setting these configurations will populate the '--help' option of your command, and provide additional validation for
# user input when invoking this command.
# This file can be removed if you want to manage input yourself.

# Command Input, Options & Flags.
#   > Input - Raw text input that normally comes after the command key.
#   > Flags - Arguments that come after the command. They take no input and must simply be placed afterwards.
#   > Options - Flags that also take input.
#
# Example: ;°ping me -n 2 -d
# Input: "me", Flag: "-d", Option: "-n" with its value being "2".
#
# This is not compulsory, but can be used to extend command versatility.
# Arguments are parsed regardless of the data entered here. If these values are populated, extra validation will be
# done upon command invocations to make sure valid options / arguments are provided.
#input:
#  requests:
#    - 'user'
#  required: false
#
#options:
#  - key: t
#    name: 'Text'
#    expects: 'Custom Text'
#    description: 'Customize the text of the hello command.'
#    accessEminence: Aficionado
#
#flags:
#  - key: d
#    name: 'DM'
#    description: 'Say hello in dms instead.'
#    accessEminence: None