language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "12"
cache:
  directories:
    - node_modules
install: npm install
env:
  global:
    - ENCRYPTION_LABEL: "af862fa96d3e"
    - COMMIT_AUTHOR_EMAIL: "aigachu.sama@gmail.com"
dist: trusty
sudo: false