name: Lavenza
command_prefix: '&'
locale: en
talents:
  - examples
  - wonderful
  - gestalt
  - dndiscord
  - paintjob
  - smashbros
  - i18n
  - minigames
clients:
  - discord
  - twitch
directory: /home/aigachu/apps/Lavenza-II/app/bots/lavenza
