#
# Project Lavenza II
# Copyright 2017-2018 Aigachu, All Rights Reserved
#
# License: https://github.com/Aigachu/Lavenza-II/blob/master/LICENSE
#

# Reader-Friendly name of the bot.
name: 'Lavenza'

# Main command prefix.
# The command prefix can be overridden per client. A default one is necessary, though.
command_prefix: '&'

# Default Locale.
# Set the default language the bot will speak in.
locale: 'en'

# Talents configuration.
# Set the list of custom talents this bot should have.
# You must enter the exact name of the directory of the custom talent.
talents:
  # Core Talents
  - examples
  - wonderful
  - gestalt
  - i18n
  - configure
  # Utility
  - paintjob
  - reminder
  - twitchnotify
  # Fun Stuff
  - minigames
  - coinflip
  - eightball
  # - cleverbot

# Clients
# Configurations for which clients this bot will access and other details.
# For each client added, a respective CLIENT_NAME.yml must be found in this directory with the client's configuration.
clients:
  - discord
  - twitch
