# Read-Friendly Name of the Talent.
name: 'Gestalt Talent'

# Talent description.
description: 'Talent used to communicate with Gestalt, the database manager in Lavenza.'

# Talent Version.
version: 1.0.0

# Path to the main class of the Talent, relative to this directory.
class: 'Gestalt'

# Set dependencies for this talent.
# This talent will not be enabled if any of its dependencies aren't enabled.
dependencies: []

# Determine which clients this talent should be enabled in.
# If unset or set to '*', this command will work on ALL CLIENTS. Be advised and plan your code accordingly.
clients: '*'