# Read-Friendly Name of the Talent.
name: 'Example Talent'

# Talent description.
description: 'Example talent that provides 1 listener and 1 command.'

# Talent Version.
version: 1.0.0

# Path to the main class of the Talent, relative to this directory.
class: 'Example.js'

# Determine which clients this talent should be enabled in.
clients: '*'

# Clients configuration.
clients.config:

  # Discord configurations.
  discord:

    # Authorization configuration.
    authorization:

      # Blacklist - Prevent use of the command in certain contexts.
      blacklist:
        guilds: []
        channels: []
        users: []

      # Whitelist - Permit use of the command in contexts where the command is globally blacklisted.
      whitelist:
        guilds: []
        channels: []
        users: []

      # Determines whether or not this command can work in direct messages with the bot.
      pms: false

      # Determines level of operation needed to use this command. A value of 0 means everyone can use it.
      oplevel: 0

    # Cooldown overrides for Discord, if needed.
    # By default, commands will have a cooldown of 5 seconds for users, and no global cooldown.
    cooldown:
      global: 0
      user: 5

#  twitch:
#    excluded_channels: []