# Services for the Commander Talent.
services:
  # Loader service for commands.
  command.loader:
    class: src/Service/CommandDirectoryLoader

  # Catalogue service for commands.
  command.catalogue:
    class: src/Service/CommandCatalogue
    priority: 97
    dependencies:
      - command.loader

  # Plugin Seeker service for commands.
  command.plugin_seeker:
    class: src/Service/CommandPluginSeeker
    dependencies:
      - command.catalogue
      - talent.catalogue
