name: DND Command
description: Central command to manage the general features of the Dungeons & Discord game!
class: Dnd
key: dnd
aliases:
  - d&d
cooldown:
  global: 0
  user: 0
clients:
  - discord
directory: /home/aigachu/apps/Lavenza-II/app/core/talents/dndiscord/hooks/Commands/Dnd
id: dnd
