# Command Input, Options & Flags.
#   > Input - Raw text input that normally comes after the command key.
#   > Flags - Arguments that come after the command. They take no input and must simply be placed afterwards.
#   > Options - Flags that also take input.
#
# Example: ;°ping me -n 2 -d
# Input: "me", Flag: "-d", Option: "-n" with its value being "2".
#
# This is not compulsory, but can be used to extend command versatility.
# Arguments are parsed regardless of the data entered here. If these values are populated, extra validation will be
# done upon command invocations to make sure valid options / arguments are provided.
#input:
#  requests:
#    - 'user'
#  required: false
#
options:
  - key: a
    name: 'Add'
    expects: 'Channel Name'
    description: 'Add a twitch channel to the list of channels that should be automatically announced in this server.'
    oplevel: 2
  - key: r
    name: 'Remove'
    expects: 'Channel Name'
    description: 'Remove a twitch channel from the list of channels that should be automatically announced in this server.'
    oplevel: 2
  - key: c
    name: 'Channel'
    expects: 'ChannelTag'
    description: 'Set the channel in this server where streams should automatically be announced.'
    oplevel: 2
flags:
  - key: s
    name: 'Status'
    description: 'Check the status of the Twitch Announcements feature. It can be Enabled or Disabled.'
    oplevel: 2
  - key: l
    name: 'List'
    description: 'List the twitch channels configured for announcements in this server.'
    oplevel: 1