name: User Picture Command
description: Easily fetch the image of a user.
class: UserPic.js
key: picture
aliases:
  - pic
  - avatar
cooldown:
  global: 0
  user: 5
clients:
  - discord
directory: >-
  /Users/kserebour/Personal/Lavenza-II/app/core/talents/minigames/hooks/Commands/UserPic
id: userpic
