#
# Project Lavenza II
# Copyright 2017-2018 Aigachu, All Rights Reserved
#
# License: https://github.com/Aigachu/Lavenza-II/blob/master/LICENSE
#

# Reader-Friendly name of the bot.
name: 'Example Boterino'

# Main command prefix.
# The command prefix can be overridden per client. A default one is necessary, though.
command_prefix: ';-'

# Talents configuration.
# Set the list of custom talents this bot should have.
# You must enter the exact name of the directory of the custom talent.
talents:
  - pingpong

# Clients
# Configurations for which clients this bot will access and other details.
clients:

  # Discord Configurations
  discord:

    # Access Rights
    # Each bot needs a set of people it will listen to above everyone else.
    # Here we have the Discord IDs of the people that should have all access rights.

    # Gods
    # Gods are the highest authority for the bot and will have access to all commands.
    # Only grant god access to people you trust.
    # They say you can only trust yourself...
    # And sometimes, you can't even trust yourself!...
    gods:
      - '77517077325287424'

    # Masters
    # They are a level under the gods, and will have access to commands with an oplevel of 2 or under.
    masters:
      - '82530619355037696'
      - '77577477425201152'
      - '81078516870819840'
      - '154750117847498752'

    # Operators are a level below masters.
    # They are a level under the masters, and will have access to commands with an oplevel of 1 or under.
    operators: []

    # Command Prefix override for Discord.
    # command_prefix: ';-d'

    # Activity to set to the bot when it's running.
    activity: ''

    # URL to add the bot to other servers.
    # This is here so that the bot can send its own URL to others.
    # If you are configuring a new bot, simply replace the 'client_id' parameter in the url and set your bot's client ID.
    # @see https://discordapp.com/developers/applications
    add_url: 'https://discordapp.com/oauth2/authorize?&client_id=1234567890&scope=bot&permissions=1546959939'

# twitch:
#   token: '12345'
#   cprefix: ';.'

# slack:
#   token: '12345'
#   cprefix: ';.'
