#
# Project Lavenza II
# Copyright 2017-2018 Aigachu, All Rights Reserved
#
# License: https://github.com/Aigachu/Lavenza-II/blob/master/LICENSE
#
# {BOT_NAME - BOT_TITLE}
#
# === Discord Info ===
# Server Add URL
#
# @see - https://discordapp.com/developers/applications/me
#



# Reader-Friendly name of the bot.
name: 'Example Boterino'

# Main command prefix.
# The command prefix can be overridden per client. A default one is necessary, though.
command_prefix: ';-'

# Talents configuration.
# Set the list of custom talents this bot should have.
# You must enter the exact name of the directory of the custom talent.
talents:
  - example

# Clients
# Configurations for which clients this bot will access and other details.
clients:

  # Discord Configurations
  discord:

    # Bot Token
    token: '12345'

    # Command Prefix override if needed.
    # command_prefix: ';-d'

    # Activity to set to the bot when it's running.
    activity: ''

    # URL to add the bot to other servers.
    # This is here so that the bot can send its own URL to others.
    add_url: 'https://discordapp.com/oauth2/authorize?&client_id=1234567890&scope=bot&permissions=1546959939'

# twitch:
#   token: '12345'
#   cprefix: '!L'

# slack:
#   token: '12345'
#   cprefix: '!L'
