name: Remind Command
description: >-
  Ask me to remind you (or someone else) about a specific action or topic
  sometime in the future!
class: Remind
key: remind
aliases: []
cooldown:
  global: 0
  user: 0
clients: '*'
directory: >-
  /Users/kserebour/Personal/Lavenza-II/app/core/talents/reminder/hooks/Commands/Remind
id: remind
