# Reader-Friendly name of the command.
name: 'Gestalt Command'

# Command description. This may be used in the bot and seen by users. Make it good!
description: 'Call certain API protocols from the bot.'

# Path to the main class containing the logic of the command, relative to this directory.
class: 'Gestalt'

# Command key. This is what users will use to invoke the command.
key: 'gestalt'

# Additional "keys" that can be used to invoke the command.
aliases:
  - 'gstlt'
  - 'gest'
  - 'gestlt'
  - 'gestl'

# Coming soon...
#input: []
#
#options: []
#

# Configure the global cooldown of the command.
# By default, commands will have a cooldown of 5 seconds.
cooldown:
  global: 5
  user: 5

# Clients where this command will function.
# If unset or set to '*', this command will work on ALL CLIENTS. Be advised and plan your code accordingly.
clients: '*'

# Client specific configurations.
clients.config:

  # Discord configurations.
  discord:

    # Authorization configuration.
    authorization:

      # Blacklist - Prevent use of the command in certain contexts.
      blacklist:
        guilds: []
        channels: []
        users: []

      # Whitelist - Permit use of the command in contexts where the command is globally blacklisted.
      whitelist:
        guilds: []
        channels: []
        users: []

      # Determines whether or not this command can work in direct messages with the bot.
      pms: false

      # Determines level of operation needed to use this command. A value of 0 means everyone can use it.
      oplevel: 0

    # Cooldown overrides for Discord, if needed.
    cooldown:
      global: 5
      user: 5

#  twitch:
#    authorization: []
#
#  slack:
#    authorization: []
