# Read-Friendly Name of the Talent.
name: 'Eight Ball'

# Talent description.
description: 'Provides commands to ask the legendary Magic 8-Ball some questions!'

# Talent Version.
version: 1.0.0

# Path to the main class of the Talent, relative to this directory.
class: 'EightBall'

# Set dependencies for this talent.
# This talent will not be enabled if any of its dependencies aren't enabled.
dependencies: []

# Determine which clients this talent should be enabled in.
# If unset or set to '*', this command will work on ALL CLIENTS. Be advised and plan your code accordingly.
clients: '*'