name: Smashies Talent
description: Provides fun commands related to Super Smash Bros!
version: 0.4.0
class: Smashbros
dependencies: []
clients: '*'
directory: /home/aigachu/apps/Lavenza-II/app/core/talents/smashbros
