name: 'Example Command'
description: 'Example command template to use when creating new commands!'

# Path to the main class containing the logic of the command
class: 'ExampleCommand'

key: 'example'

aliases:
  - 'exmpl'
  - 'examplez'

input: []

options: []

cooldown:
  global: 0
  user: 0

clients: '*'

clients_config:
  discord:
    authorization:
      guilds: []
      channels: []
      pms: false
      users: []
      oplevel: 0
      cooldown:
        global: 0
        user: 0

  twitch:
    authorization: []

  slack:
    authorization: []
