# Reader-Friendly name of the command.
name: 'Remind Command'

# Command description. This may be used in the bot and seen by users. Make it good!
description: 'Ask me to remind you (or someone else) about a specific action or topic sometime in the future!'

# Path to the main class containing the logic of the command, relative to this directory.
class: 'Remind'

# Command key. This is what users will use to invoke the command.
key: 'remind'

# Additional "keys" that can be used to invoke the command.
aliases: []

# Configure the global cooldown of the command.
# By default, commands will have a cooldown of 5 seconds for users, and no global cooldown.
cooldown:
  global: 0
  user: 0

# Clients where this command will function.
# If unset or set to '*', this command will work on ALL CLIENTS. Be advised and plan your code accordingly.
clients: '*'
