name: Dungeons & Discord Talent
description: The ultimate Dungeons & Discord feature!
version: 1.0.0
class: DnDiscord
dependencies: []
clients:
  - discord
directory: /home/aigachu/apps/Lavenza-II/app/core/talents/dndiscord
