# Read-Friendly Name of the Talent.
name: 'Minigames Talent'

# Talent description.
description: 'Provides a wide range of fun commands to use.'

# Talent Version.
version: 1.0.0

# Path to the main class of the Talent, relative to this directory.
class: 'Minigames'

# Set dependencies for this talent.
# This talent will not be enabled if any of its dependencies aren't enabled.
dependencies: []

# Determine which clients this talent should be enabled in.
clients: '*'