name: Minigames Talent
description: Provides a wide range of fun commands to use.
version: 1.0.0
class: Minigames
dependencies: []
clients: '*'
directory: /home/aigachu/apps/Lavenza-II/app/core/talents/minigames
