# Read-Friendly Name of the Talent.
name: 'Reminder Talent'

# Talent description.
description: 'Provides the capability to remind discord members about things they have to do in the future!'

# Talent Version.
version: 0.2.0

# Path to the main class of the Talent, relative to this directory.
class: 'Reminder'

# Determine which clients this talent should be enabled in.
clients:
  - discord