# Services for the Commander Talent.
services:
  # Loader service for commands.
  listener.loader:
    class: src/Service/ListenerFileLoader

  # Catalogue service for listeners.
  listener.catalogue:
    class: src/Service/ListenerCatalogue
    priority: 97
    dependencies:
      - listener.loader

  # Plugin Seeker service for listeners.
  listener.plugin_seeker:
    class: src/Service/ListenerPluginSeeker
    dependencies:
      - listener.catalogue
      - talent.catalogue
