# Read-Friendly Name of the Talent.
name: 'Reminder Talent'

# Talent description.
description: 'Provides the capability to remind discord members about things they have to do in the future!'

# Talent Version.
version: 0.2.0

# Path to the main class of the Talent, relative to this directory.
class: 'Reminder'

# Set dependencies for this talent.
# This talent will not be enabled if any of its dependencies aren't enabled.
dependencies: []

# Determine which clients this talent should be enabled in.
# If unset or set to '*', this command will work on ALL CLIENTS. Be advised and plan your code accordingly.
clients:
  - discord