name: Remind Command (WORK IN PROGRESS)
description: >-
  Ask me to remind you or someone else about a specific action or topic,
  sometime in the future! You can either remind yourself or someone else.
class: Remind
key: remind
aliases: []
cooldown:
  global: 0
  user: 0
clients:
  - discord
clients.config:
  discord:
    authorization:
      blacklist:
        guilds: []
        channels: []
        users: []
      whitelist:
        guilds: []
        channels: []
        users: []
      pms: false
      oplevel: 0
    cooldown:
      global: 0
      user: 0
directory: >-
  /Users/kserebour/src/Personal/Lavenza-II/app/core/talents/reminder/hooks/Commands/Remind
id: remind
