# Reader-Friendly name of the command.
name: 'Config Command'

# Command description. This may be used in the bot and seen by users. Make it good!
description: 'Command that simply orders the bot to say "Hello!"'

# Path to the main class containing the logic of the command, relative to this directory.
class: 'Config'

# Command key. This is what users will use to invoke the command.
key: 'config'

# Additional "keys" that can be used to invoke the command.
aliases:
  - 'conf'

# Command Input, Options & Flags.
#   > Input - Raw text input that normally comes after the command key.
#   > Flags - Arguments that come after the command. They take no input and must simply be placed afterwards.
#   > Options - Flags that also take input.
#
# Example: ;°ping me -n 2 -d
# Input: "me", Flag: "-d", Option: "-n" with its value being "2".
#
# This is not compulsory, but can be used to extend command versatility.
# Arguments are parsed regardless of the data entered here. If these values are populated, extra validation will be
# done upon command invocations to make sure valid options / arguments are provided.
#input:
#  requests:
#    - 'user'
#  required: false
#
#options:
#  - key: t
#    name: 'Text'
#    expects: 'Custom Text'
#    description: 'Customize the text of the hello command.'
#    oplevel: 1
#
#flags:
#  - key: d
#    name: 'DM'
#    description: 'Say hello in dms instead.'
#    oplevel: 0

# Configure the global cooldown of the command.
# By default, commands will have a cooldown of 5 seconds for users, and no global cooldown.
cooldown:
  global: 0
  user: 0

# Clients where this command will function.
# If unset or set to '*', this command will work on ALL CLIENTS. Be advised and plan your code accordingly.
clients: '*'

# Client specific configurations.
clients.config:

  # Discord configurations.
  discord:
    # Authorization configuration.
    authorization:

      # Blacklist - Prevent use of the command in certain contexts.
      blacklist:
        guilds: []
        channels: []
        users: []

      # Whitelist - Permit use of the command in contexts where the command is globally blacklisted.
      whitelist:
        guilds: []
        channels: []
        users: []

      # Determines whether or not this command can work in direct messages with the bot.
      pms: false

      # Determines level of operation needed to use this command. A value of 0 means everyone can use it.
      oplevel: 2

    # Configure the global cooldown of the command.
    # By default, commands will have a cooldown of 5 seconds for users, and no global cooldown.
    cooldown:
      global: 0
      user: 5

#  twitch:
#    authorization: []
#
#  slack:
#    authorization: []
