name: Boot Command
description: Boot a bot part of the codebase.
class: Boot
key: boot
aliases:
  - summon
  - activate
cooldown:
  global: 0
  user: 0
clients: '*'
directory: /home/aigachu/apps/Lavenza-II/app/core/talents/master/hooks/Commands/Boot
id: boot
