# Reader-Friendly name of the command.
name: 'Config Export Command'

# Command description. This may be used in the bot and seen by users. Make it good!
description: 'Exports all configurations to the repository.'

# Path to the main class containing the logic of the command, relative to this directory.
class: 'ConfigExport'

# Command key. This is what users will use to invoke the command.
key: 'config-export'

# Additional "keys" that can be used to invoke the command.
aliases:
  - 'cex'

# Coming soon...
#input: []
#
#options: []
#
#cooldown:
#  global: 0
#  user: 0

# Clients where this command will function.
# If unset or set to '*', this command will work on ALL CLIENTS. Be advised and plan your code accordingly.
clients: '*'

# Client specific configurations.
clients_config:

  # Discord configurations.
  discord:
    # Authorizations
    authorization:
      # Servers where this command can work. If empty, works everywhere.
      guilds: []
      # Channels where this command can work. If empty, works everywhere.
      channels: []
      # Determines whether or not this command can work in direct messages with the bot.
      pms: false
      # Determines which users can use this command.
      users: []
      # Determines level of operation needed to use this command. A value of 0 means everyone can use it.
      oplevel: 0

    # Cooldown times in seconds.
    # global - all user cooldown.
    # user - user specific cooldown.
    cooldown:
      global: 0
      user: 0

#  twitch:
#    authorization: []
#
#  slack:
#    authorization: []
