name: Paint Command
description: Add colors to your server and allow users to use them!
class: Paint
key: paint
aliases:
  - color
  - col
cooldown:
  global: 0
  user: 0
clients:
  - discord
directory: /home/aigachu/apps/Lavenza-II/app/core/talents/paintjob/hooks/Commands/Paint
id: paint
