# Command Input, Options & Flags.
#   > Input - Raw text input that normally comes after the command key.
#   > Flags - Arguments that come after the command. They take no input and must simply be placed afterwards.
#   > Options - Flags that also take input.
#
# Example: ;°ping me -n 2 -d
# Input: "me", Flag: "-d", Option: "-n" with its value being "2".
#
# This is not compulsory, but can be used to extend command versatility.
# Arguments are parsed regardless of the data entered here. If these values are populated, extra validation will be
# done upon command invocations to make sure valid options / arguments are provided.
#input:
#  requests:
#    - 'user'
#  required: false

options:
  - key: c
    name: 'Create'
    expects: 'Color Hex'
    description: 'Create a color that can be used by users in this server.'
    oplevel: 1
  - key: s
    name: 'Set'
    expects: 'Hex/Name/Role'
    description: 'Assign a color to yourself! Make sure the color exists. :)'
    oplevel: 0

flags:
  - key: l
    name: 'List'
    description: 'List the custom colors available in this server.'
    oplevel: 0
  - key: r
    name: 'Remove'
    description: 'Remove a color from yourself only!'
    oplevel: 0
  - key: x
    name: 'Delete All'
    description: 'Delete all color roles from this server...But that would suck right? :('
    oplevel: 1