options:
  - key: a
    name: Add
    expects: Channel Name
    description: >-
      Add a twitch channel to the list of channels that should be automatically
      announced in this server.
    oplevel: 1
  - key: r
    name: Remove
    expects: Channel Name
    description: >-
      Remove a twitch channel from the list of channels that should be
      automatically announced in this server.
    oplevel: 1
  - key: c
    name: Channel
    expects: ChannelTag
    description: >-
      Set the channel in this server where streams should automatically be
      announced.
    oplevel: 1
flags:
  - key: s
    name: Status
    description: >-
      Check the status of the Twitch Announcements feature. It can be Enabled or
      Disabled.
    oplevel: 1
