# Read-Friendly Name of the Talent.
name: 'Ping Pong Talent'

# Talent description.
description: 'Give bot the ability to say "Pong!" when it hears "Ping!" from anyone.'

# Talent Version.
version: 1.0.0

# Path to the main class of the Talent, relative to this directory.
class: 'PingPong'

# Determine which clients this talent should be enabled in.
clients: '*'

# Clients configuration.
clients.config:
  discord:
    enabled: true
    authorization:
      blacklist:
        all: false
        guilds: []
        channels: []
      whitelist:
        all: false
        guilds: []
        channels: []

#  twitch:
#    excluded_channels: []