# Read-Friendly Name of the Talent.
name: 'Ping Pong Talent'

# Talent description.
description: 'Give bot the ability to say "Pong!" when it hears "Ping!" from anyone.'

# Talent Version.
version: 1.0.0

# Path to the main class of the Talent, relative to this directory.
class: 'PingPong'
